var MupsJson = {
    "0": {
        "mapunit": "Trc",
        "name": "Chinle Formation",
        "nameDMU": "Chinle Formation (Late Triassic, 210-230 Ma)",
        "description": "Colorful mudstone, such as in the Painted Desert, and less abundant lenses of sandstone and conglomerate, deposited by a large river system. This unit typically is eroded into badlands topography and contains clays that are prone to shrinking and swelling.",
        "age": "Late Triassic",
        "b_age": 210,
        "t_age": 230,
        "age_unit": "Ma",
        "rgb": "rgb(125,255,209)"
    },
    "1": {
        "mapunit": "Ks",
        "name": "Cretaceous Sedimentary rocks",
        "nameDMU": "Cretaceous Sedimentary rocks (about 88-97 Ma)",
        "description": "Tan sandstone (Dakota Sandstone) overlain by gray shale (Mancos Shale); deposited in beach, river delta, and shallow sea settings. The Mancos Shale is overlain by the Mesaverde Group (map unit Kmv). This unit includes related sandstone and shale exposed near Show Low, Morenci (Pinkard Formation), and around Deer Creek south of Globe.",
        "age": "Cretaceous",
        "b_age": 88,
        "t_age": 97,
        "age_unit": "Ma",
        "rgb": "rgb(179,251,133)"
    },
    "2": {
        "mapunit": "KJs",
        "name": "Cretaceous to Upper Jurassic Sedimentary rocks with minor volcanic rocks",
        "nameDMU": "Cretaceous to Upper Jurassic Sedimentary rocks with minor volcanic rocks (80-160 Ma)",
        "description": "Sandstone and conglomerate, rarely forms prominent outcrops; massive conglomerate is typical near base of unit and locally in upper part. These deposits are nonmarine except in southeastern Arizona, where prominent gray marine limestone (Mural Limestone) forms the middle of the Bisbee Group. Sandstones are typically medium-bedded, drab brown, lithic-feldspathic arenites. Includes Bisbee Group (largely Early Cretaceous) and related rocks, Temporal, Bathtub, and Sand Wells formations, rocks of Gu Achi, McCoy Mountains Formation, and Upper Cretaceous Fort Crittenden Formation and equivalent rocks.",
        "age": "Cretaceous to Upper Jurassic",
        "b_age": 80,
        "t_age": 160,
        "age_unit": "Ma",
        "rgb": "rgb(186,255,158)"
    },
    "3": {
        "mapunit": "QTs",
        "name": "Early Pleistocene to late Miocene basin deposits",
        "nameDMU": "Early Pleistocene to late Miocene basin deposits (0.75-10 Ma)",
        "description": "Poorly sorted, variably consolidated gravel and sand that range widely in age. These sediments are generally light gray or tan. This unit is generally mapped in areas of deep late Cenozoic stream incision and landscape degradation where thin Quaternary deposits (map units Qy, Qm, Qo) discontinuously blanket older deposits (map units Tsy or Tsm) and the two cannot be differentiated at the scale of this map.",
        "age": "Early Pleistocene to Late Miocene",
        "b_age": 0.75,
        "t_age": 10,
        "age_unit": "Ma",
        "rgb": "rgb(255,232,186)"
    },
    "4": {
        "mapunit": "Qo",
        "name": "Early Pleistocene to latest Pliocene surficial deposits",
        "nameDMU": "Early Pleistocene to latest Pliocene surficial deposits (0.75-3 Ma)",
        "description": "Coarse relict alluvial fan deposits that form rounded ridges or flat, isolated surfaces that are moderately to deeply incised by streams. These deposits are generally topographically high and have undergone substantial erosion. Deposits are moderately to strongly consolidated, and commonly contain coarser grained sediment than younger deposits in the same area.",
        "age": "Early Pleistocene to Late Pliocene",
        "b_age": 0.75,
        "t_age": 3,
        "age_unit": "Ma",
        "rgb": "rgb(253,252,155)"
    },
    "5": {
        "mapunit": "Xg",
        "name": "Early Proterozoic Granitic rocks",
        "nameDMU": "Early Proterozoic Granitic rocks (1600-1800 Ma)",
        "description": "Wide variety of granitic rocks, including granite, granodiorite, tonalite, quartz diorite, diorite, and gabbro. These rocks commonly are characterized by steep, northeast-striking foliation.",
        "age": "Early Proterozoic",
        "b_age": 1600,
        "t_age": 1800,
        "age_unit": "Ma",
        "rgb": "rgb(186,130,123)"
    },
    "6": {
        "mapunit": "Xm",
        "name": "Early Proterozoic Metamorphic rocks",
        "nameDMU": "Early Proterozoic Metamorphic rocks (1600-1800 Ma)",
        "description": "Undivided metasedimentary, metavolcanic, and gneissic rocks.",
        "age": "Early Proterozoic",
        "b_age": 1600,
        "t_age": 1800,
        "age_unit": "Ma",
        "rgb": "rgb(178,178,95)"
    },
    "7": {
        "mapunit": "Xms",
        "name": "Early Proterozoic Metasedimentary rocks",
        "nameDMU": "Early Proterozoic Metasedimentary rocks (1600-1800 Ma)",
        "description": "Metasedimentary rocks, mostly derived from sandstone and shale, with minor conglomerate and carbonate rock. Includes quartz-rich, mostly non-volcanic Pinal Schist in southeastern Arizona and variably volcanic-lithic sedimentary rocks in the Yavapai and Tonto Basin supergroups in central Arizona.",
        "age": "Early Proterozoic",
        "b_age": 1600,
        "t_age": 1800,
        "age_unit": "Ma",
        "rgb": "rgb(185,196,185)"
    },
    "8": {
        "mapunit": "Xmv",
        "name": "Early Proterozoic Metavolcanic rocks",
        "nameDMU": "Early Proterozoic Metavolcanic rocks (1650 to 1800 Ma)",
        "description": "Weakly to strongly metamorphosed volcanic rocks. Protoliths include basalt, andesite, dacite, and rhyolite deposited as lava or tuff, related sedimentary rock, and shallow intrusive rock. These rocks, widely exposed in several belts in central Arizona, include metavolcanic rocks in the Yavapai and Tonto Basin supergroups.",
        "age": "Early Proterozoic",
        "b_age": 1650,
        "t_age": 1800,
        "age_unit": "Ma",
        "rgb": "rgb(144,179,136)"
    },
    "9": {
        "mapunit": "Xq",
        "name": "Early Proterozoic Quartzite",
        "nameDMU": "Early Proterozoic Quartzite (1650? -1700 Ma)",
        "description": "Brown to maroon, resistant quartzite and minor conglomerate of the Mazatzal Group, exposed primarily in the Payson area.",
        "age": "Early Proterozoic",
        "b_age": 1650,
        "t_age": 1700,
        "age_unit": "Ma",
        "rgb": "rgb(146,179,95)"
    },
    "10": {
        "mapunit": "TKg",
        "name": "Early Tertiary to Late Cretaceous Granitic rocks",
        "nameDMU": "Early Tertiary to Late Cretaceous Granitic rocks (50-82 Ma)",
        "description": "Porphyritic to equigranular granite to diorite emplaced during the Laramide orogeny. Larger plutons are characteristically medium-grained, biotite +/- hornblende granodiorite to granite. Smaller, shallow-level intrusions are typically porphyritic. Most of the large copper deposits in Arizona are associated with porphyritic granitic rocks of this unit, and are thus named ‘porphyry copper deposits’.",
        "age": "Early Tertiary to Late Cretaceous",
        "b_age": 50,
        "t_age": 82,
        "age_unit": "Ma",
        "rgb": "rgb(253,119,101)"
    },
    "11": {
        "mapunit": "TKgm",
        "name": "Early Tertiary to Late Cretaceous Muscovite-bearing Granitic rocks",
        "nameDMU": "Early Tertiary to Late Cretaceous Muscovite-bearing Granitic rocks (50-80 Ma)",
        "description": "Light-colored peraluminous muscovite granite with or without garnet; commonly forms sills and is associated with abundant pegmatite dikes and sills. This unit includes granites in the Harcuvar and Harquahala Mountains of western Arizona and in the Santa Catalina, Rincon, Tortolita, Picacho, and Coyote Mountains of south-central Arizona. These granites typically represent the youngest phase of voluminous magmatism during the Laramide orogeny in Arizona. This unit also includes several muscovite-bearing granites in southern Arizona that are associated with calc-alkaline granites of unit TKg, and a batholith in the Cabeza Prieta area of southwestern Arizona.",
        "age": "Early Tertiary to Late Cretaceous",
        "b_age": 50,
        "t_age": 80,
        "age_unit": "Ma",
        "rgb": "rgb(255,135,145)"
    },
    "12": {
        "mapunit": "Kv",
        "name": "Early Tertiary to Late Cretaceous Volcanic rocks",
        "nameDMU": "Early Tertiary to Late Cretaceous Volcanic rocks (50-82 Ma)",
        "description": "Rhyolite to andesite and closely associated sedimentary and near-surface intrusive rocks; commonly dark gray to dark greenish gray or greenish brown. In the ranges west of Tucson, this unit includes thick welded ash-flow tuffs. Volcanic rocks of this unit are inferred to be derived from vents and volcanoes above magma chambers that solidified to form the granitic rocks of map unit TKg. These rocks are restricted to southeastern Arizona except for a small outcrop near Bagdad.",
        "age": "Early Tertiary to Late Cretaceous",
        "b_age": 50,
        "t_age": 82,
        "age_unit": "Ma",
        "rgb": "rgb(209,255,135)"
    },
    "13": {
        "mapunit": "Jgc",
        "name": "Glen Canyon Group",
        "nameDMU": "Glen Canyon Group (Early Jurassic, about 180-210 Ma)",
        "description": "Conspicuous red, cross-bedded Wingate Sandstone and the conspicuously cross-bedded, eolian, red to buff Navajo Sandstone form prominent cliffs in northern Arizona. These two sandstone units are separated by variably colored siltstone, silty sandstone, and sandstone of the Kayenta and Moenave Formations.",
        "age": "Early Jurassic",
        "b_age": 180,
        "t_age": 210,
        "age_unit": "Ma",
        "rgb": "rgb(109,241,168)"
    },
    "14": {
        "mapunit": "Qr",
        "name": "Holocene river alluvium",
        "nameDMU": "Holocene river alluvium (0-10 ka)",
        "description": "Unconsolidated to weakly consolidated sand and gravel in river channels and sand, silt, and clay on floodplains. Also includes young terrace deposits fringing floodplains.",
        "age": "Holocene",
        "b_age": 0,
        "t_age": 10,
        "age_unit": "ka",
        "rgb": "rgb(255,255,186)"
    },
    "15": {
        "mapunit": "Qy",
        "name": "Holocene Surficial Deposits",
        "nameDMU": "Holocene Surficial Deposits (0-10 ka)",
        "description": "Unconsolidated deposits associated with modern fluvial systems. This unit consists primarily of fine-grained, well-sorted sediment on alluvial plains, but also includes gravelly channel, terrace, and alluvial fan deposits on middle and upper piedmonts.",
        "age": "Holocene",
        "b_age": 0,
        "t_age": 10,
        "age_unit": "ka",
        "rgb": "rgb(255,255,227)"
    },
    "16": {
        "mapunit": "QTb",
        "name": "Holocene to middle Pliocene Basaltic rocks",
        "nameDMU": "Holocene to middle Pliocene Basaltic rocks (0-4 Ma)",
        "description": "Mostly dark-colored basaltic lava and cinders young enough that some original volcanic landforms are still apparent.   Includes a small amount of andesite, dacite, and rhyolite.   Rocks of this map unit are largely restricted to six areas widely distributed in Arizona: San Francisco and Uinkaret volcanic fields in northern Arizona (0-4 Ma); Springerville (0-4 Ma) and San Carlos (0-2 Ma) volcanic fields in east-central Arizona; and San Bernardino (0-1 Ma) and Sentinel (1-4 Ma) volcanic fields in southern Arizona.   Rocks of this unit are also present in the extreme southwestern part of Arizona where they were erupted at the edge of the Pinacate volcanic field (0-2 Ma) in northwestern Sonora.",
        "age": "Holocene to Middle Pliocene",
        "b_age": 0,
        "t_age": 4,
        "age_unit": "Ma",
        "rgb": "rgb(240,213,240)"
    },
    "17": {
        "mapunit": "QTv",
        "name": "Holocene to middle Pliocene Volcanic rocks",
        "nameDMU": "Holocene to middle Pliocene Volcanic rocks (0-4 Ma)",
        "description": "Rhyolite to andesite deposited as a sequence of lava flows and associated rocks; generally light to medium gray, tan, or reddish brown. These rocks are part of the San Francisco volcanic field.",
        "age": "Holocene to Middle Pliocene",
        "b_age": 0,
        "t_age": 4,
        "age_unit": "Ma",
        "rgb": "rgb(227,196,240)"
    },
    "18": {
        "mapunit": "JTr",
        "name": "Jurassic and Triassic Sedimentary and Volcanic rocks",
        "nameDMU": "Jurassic and Triassic Sedimentary and Volcanic rocks (160-240 Ma)",
        "description": "Undivided massive quartz-feldspar porphyry of the Jurassic Planet Volcanics, quartz-rich metasandstone of the Jurassic Vampire Formation, and quartzite, phyllite, and fine grained, variably calcareous metasiltstone of the Triassic Buckskin Formation; exposed primarily in the Buckskin and Rawhide Mountains of western Arizona. This unit also includes sandstone and conglomerate beneath Jurassic volcanic rocks in the central Dome Rock Mountains.",
        "age": "Jurassic to Triassic",
        "b_age": 160,
        "t_age": 240,
        "age_unit": "Ma",
        "rgb": "rgb(178,255,240)"
    },
    "19": {
        "mapunit": "Jg",
        "name": "Jurassic Granitic rocks",
        "nameDMU": "Jurassic Granitic rocks (150-180 Ma)",
        "description": "Granite to diorite, locally foliated and locally alkalic; includes Triassic(?) granitoids in the Trigo Mountains. This unit includes two dominant assemblages of igneous rocks. The Kitt Peak-Trigo Peaks super-unit includes, from oldest to youngest: dark, foliated or gneissic diorite, medium-grained equigranular to porphyritic granodiorite, and small, irregular intrusions of light-colored, fine-grained granite. The Ko Vaya super-unit, limited to south-central Arizona, includes texturally heterogeneous K-feldspar-rich granitic rocks.",
        "age": "Jurassic",
        "b_age": 150,
        "t_age": 180,
        "age_unit": "Ma",
        "rgb": "rgb(228,95,176)"
    },
    "20": {
        "mapunit": "Jvs",
        "name": "Jurassic Sedimentary and Volcanic rocks",
        "nameDMU": "Jurassic Sedimentary and Volcanic rocks (150-170 Ma)",
        "description": "Sandstone and conglomerate derived from volcanic rocks with associated intermediate-composition lava flows, breccias, and tuffs.   In southern Arizona this unit includes rocks of the Artesa sequence, Pitoikam Formation, Mulberry Wash volcanics, Rudolfo Red Beds, Recreation Red Beds, and Gardner Canyon Formation. In western Arizona it includes the Harquar Formation, rocks of Slumgullion, and related(?) unnamed units in the Kofa and Middle Mountains. This unit is characterized by maroon, brown, and purplish-gray volcanic-lithic sandstone and siltstone, with subordinate to abundant conglomerate, quartz-rich sandstone and sparse limestone.",
        "age": "Jurassic",
        "b_age": 150,
        "t_age": 170,
        "age_unit": "Ma",
        "rgb": "rgb(125,255,178)"
    },
    "21": {
        "mapunit": "MzPz",
        "name": "Jurassic to Cambrian Metamorphosed Sedimentary rocks",
        "nameDMU": "Jurassic to Cambrian Metamorphosed Sedimentary rocks (160-540 Ma)",
        "description": "Highly faulted and folded rocks of units Jv, J2, and Pz, deformed and metamorphosed in Jurassic, Cretaceous and Tertiary time. This unit is restricted to west-central Arizona.",
        "age": "Jurassic to Cambrian",
        "b_age": 160,
        "t_age": 540,
        "age_unit": "Ma",
        "rgb": "rgb(129,253,128)"
    },
    "22": {
        "mapunit": "Jv",
        "name": "Jurassic Volcanic rocks",
        "nameDMU": "Jurassic Volcanic rocks (160-200 Ma)",
        "description": "Massive quartz-feldspar porphyry, generally interpreted as thick, welded rhyolitic tuffs, with locally abundant lava, and sandstone and conglomerate derived from volcanic rocks. Rare eolian quartzite units are interbedded in southern Arizona. Includes Ali Molina Formation, Mount Wrightson Formation, part of the Canelo Hills Volcanics, Cobre Ridge tuff, Black Rock volcanics, Planet Volcanics, and equivalent rocks.",
        "age": "Jurassic",
        "b_age": 160,
        "t_age": 200,
        "age_unit": "Ma",
        "rgb": "rgb(125,255,178)"
    },
    "23": {
        "mapunit": "Qm",
        "name": "Late and Middle Pleistocene Surficial Deposits",
        "nameDMU": "Late and Middle Pleistocene Surficial Deposits (10-750 ka)",
        "description": "Unconsolidated to weakly consolidated alluvial fan, terrace, and basin-floor deposits with moderate to strong soil development. Fan and terrace deposits are primarily poorly sorted, moderately bedded gravel and sand, and basin-floor deposits are primarily sand, silt, and clay.",
        "age": "Late to Middle Pleistocene",
        "b_age": 10,
        "t_age": 750,
        "age_unit": "ka",
        "rgb": "rgb(255,255,186)"
    },
    "24": {
        "mapunit": "Tb",
        "name": "Late to middle Miocene Basaltic Rocks",
        "nameDMU": "Late to middle Miocene Basaltic Rocks (8-16 Ma)",
        "description": "Mostly dark, mesa-forming basalt deposited as lava flows. Rocks of this unit are widely exposed south of Camp Verde (Hickey Formation basalts), in the Mohon Mountains north of Bagdad, “The Mesa” east of Parker, and at other scattered locations in western Arizona. Rocks of this unit were not tilted by middle-Tertiary normal faulting except in a narrow belt from north of Phoenix to the northwest corner of the state.",
        "age": "Late to Middle Miocene",
        "b_age": 8,
        "t_age": 16,
        "age_unit": "Ma",
        "rgb": "rgb(255,158,227)"
    },
    "25": {
        "mapunit": "Tg",
        "name": "Middle Miocene to Oligocene Granitic rocks",
        "nameDMU": "Middle Miocene to Oligocene Granitic rocks (14-26 Ma)",
        "description": "Granite to diorite representing solidified magma chambers that were the likely source of overlying and nearby volcanic rocks of map unit Tv. The granitic rocks are typically equigranular and fine- to medium-grained.",
        "age": "Middle Miocene to Oligocene",
        "b_age": 14,
        "t_age": 26,
        "age_unit": "Ma",
        "rgb": "rgb(251,186,123)"
    },
    "26": {
        "mapunit": "Tsm",
        "name": "Middle Miocene to Oligocene Sedimentary rocks",
        "nameDMU": "Middle Miocene to Oligocene Sedimentary rocks (11-32 Ma)",
        "description": "Conglomerate, sandstone, mudstone, limestone, and rock-avalanche breccia (sheet-like deposits of crushed rock) deposited and tilted during widespread normal faulting and basin development. Sediments, mostly conglomerate and sandstone, are commonly medium to dark brown, reddish brown, or brownish gray; younger strata are generally lighter colors. Most deposits are 20 to 30 Ma in southeastern Arizona and 15 to 25 Ma in central and western Arizona.",
        "age": "Middle Miocene to Oligocene",
        "b_age": 11,
        "t_age": 32,
        "age_unit": "Ma",
        "rgb": "rgb(226,184,84)"
    },
    "27": {
        "mapunit": "Ti",
        "name": "Middle Miocene to Oligocene Shallow Intrusions",
        "nameDMU": "Middle Miocene to Oligocene Shallow Intrusions (14-35 Ma)",
        "description": "Generally very fine-grained, porphyritic rhyolite to dacite in small, irregular-shaped bodies formed as subvolcanic intrusions in volcanic fields of southern and western Arizona, or in concentrated zones of dikes in the Mohave and Black Mountains of northwestern Arizona. The unit consists of mafic tuff, breccia and shallow intrusions at Buell Park in northeastern Arizona.",
        "age": "Middle Miocene to Oligocene",
        "b_age": 14,
        "t_age": 35,
        "age_unit": "Ma",
        "rgb": "rgb(253,158,105)"
    },
    "28": {
        "mapunit": "Tvs",
        "name": "Middle Miocene to Oligocene Volcanic and Sedimentary rocks, undivided",
        "nameDMU": "Middle Miocene to Oligocene Volcanic and Sedimentary rocks, undivided (11-32 Ma)",
        "description": "Sequences of diverse volcanic rocks with abundant interbedded sedimentary rocks.",
        "age": "Middle Miocene to Oligocene",
        "b_age": 11,
        "t_age": 32,
        "age_unit": "Ma",
        "rgb": "rgb(251,196,123)"
    },
    "29": {
        "mapunit": "Tv",
        "name": "Middle Miocene to Oligocene Volcanic rocks",
        "nameDMU": "Middle Miocene to Oligocene Volcanic rocks (11-38 Ma)",
        "description": "Lava, tuff, fine-grained intrusive rock, and diverse pyroclastic rocks. These compositionally variable volcanic rocks include basalt, andesite, dacite, and rhyolite. Thick felsic volcanic sequences form prominent cliffs and range fronts in the Black (Mohave County), Superstition, Kofa, Eagletail, Galiuro, and Chiricahua Mountains. This unit includes regionally extensive ash-flow tuffs, such as the Peach Springs tuff of northwestern Arizona and the Apache Leap tuff east of Phoenix. Most volcanic rocks are 20-30 Ma in southeastern Arizona and 15 to 25 Ma in central and western Arizona, but this unit includes some late Eocene rocks near the New Mexico border in east-central Arizona.",
        "age": "Middle Miocene to Oligocene",
        "b_age": 11,
        "t_age": 38,
        "age_unit": "Ma",
        "rgb": "rgb(253,193,88)"
    },
    "30": {
        "mapunit": "Yd",
        "name": "Middle Proterozoic Diabase",
        "nameDMU": "Middle Proterozoic Diabase (1050-1150 Ma)",
        "description": "Dark gray to black sills (intrusions mostly parallel to bedding) in strata of the Apache Group and irregular to sheet-like intrusions in other rocks. Present in east-central and southeastern Arizona. Some sills are more than 100 m thick. Exposures are extensive north of Globe.",
        "age": "Middle Proterozoic",
        "b_age": 1050,
        "t_age": 1150,
        "age_unit": "Ma",
        "rgb": "rgb(213,151,208)"
    },
    "31": {
        "mapunit": "Yg",
        "name": "Middle Proterozoic Granitic rocks",
        "nameDMU": "Middle Proterozoic Granitic rocks (1400-1450 Ma)",
        "description": "Mostly porphyritic biotite granite with large microcline phenocrysts, with local fine-grained border phases and aplite. Associated pegmatite and quartz veins are rare. This unit forms large plutons, including the Oracle Granite, Ruin Granite, granite in the Pinnacle Peak - Carefree area northeast of Phoenix, and several bodies west of Prescott.",
        "age": "Middle Proterozoic",
        "b_age": 1400,
        "t_age": 1450,
        "age_unit": "Ma",
        "rgb": "rgb(202,139,79)"
    },
    "32": {
        "mapunit": "Ys",
        "name": "Middle Proterozoic Sedimentary rocks",
        "nameDMU": "Middle Proterozoic Sedimentary rocks (700-1300)",
        "description": "Red-brown shale and sandstone, buff to orange quartzite, limestone, basalt, black shale, and sparse conglomerate. This unit includes the Grand Canyon Supergroup, Apache Group, and Troy Quartzite. These rocks were deposited in shallow marine, coastal nonmarine, and fluvial settings.",
        "age": "Middle Proterozoic",
        "b_age": 700,
        "t_age": 1300,
        "age_unit": "Ma",
        "rgb": "rgb(186,178,255)"
    },
    "33": {
        "mapunit": "MC",
        "name": "Mississippian, Devonian, and Cambrian Sedimentary rocks",
        "nameDMU": "Mississippian, Devonian, and Cambrian Sedimentary rocks (330-540 Ma)",
        "description": "Brown to dark gray sandstone grades upward into green and gray shale, overlain by light to medium gray or tan limestone and dolostone. This unit includes the Tapeats Sandstone, Bright Angel Shale, Muav Limestone, Temple Butte Formation and Redwall Limestone in northern Arizona, and the Bolsa Quartzite, Abrigo Formation, Martin Formation, and Escabrosa Limestone in southern Arizona. These rocks record intermittent sea-level rise and inundation in early Paleozoic time.",
        "age": "Mississippian to Cambrian",
        "b_age": 330,
        "t_age": 540,
        "age_unit": "Ma",
        "rgb": "rgb(196,217,240)"
    },
    "34": {
        "mapunit": "Trm",
        "name": "Moenkopi Formation",
        "nameDMU": "Moenkopi Formation (Middle(?) and Early Triassic, 230-245 Ma)",
        "description": "Dark red sandstone and mudstone; includes gypsum beds in northwestern Arizona; deposited on a low-relief coastal plain.",
        "age": "Middle to Early Triassic",
        "b_age": 230,
        "t_age": 245,
        "age_unit": "Ma",
        "rgb": "rgb(144,222,212)"
    },
    "35": {
        "mapunit": "Jm",
        "name": "Morrison Formation",
        "nameDMU": "Morrison Formation (Late Jurassic, about 145-160 Ma)",
        "description": "Commonly cliff-forming, cross-bedded sandstone lenses alternating with slope-forming siltstone, mudstone and shale. Colors are highly variable, and include greenish gray, reddish brown, pink, white, and purple. Sands were deposited by braided streams with finer sediment representing overbank or lacustrine deposits.",
        "age": "Late Jurassic",
        "b_age": 145,
        "t_age": 160,
        "age_unit": "Ma",
        "rgb": "rgb(120,240,119)"
    },
    "36": {
        "mapunit": "Tso",
        "name": "Oligocene to Paleocene Sedimentary rocks",
        "nameDMU": "Oligocene to Paleocene[?] Sedimentary rocks (30-65 Ma)",
        "description": "Light colored, weakly to moderately consolidated conglomerate and sandstone deposited largely or entirely before mid-Tertiary volcanism and extensional faulting. Most sediment was deposited by early Cenozoic streams that flowed northeastward onto the Colorado Plateau from areas to the southwest that are now lower in elevation than the Plateau. Sediments of this map unit, other than the Chuska Sandstone in northeasternmost Arizona, are commonly referred to as “rim gravels” because they now rest on or near the Mogollon Rim, which is the southwestern edge of the Colorado Plateau.",
        "age": "Oligocene to Paleocene",
        "b_age": 30,
        "t_age": 65,
        "age_unit": "Ma",
        "rgb": "rgb(238,215,146)"
    },
    "37": {
        "mapunit": "KJo",
        "name": "Orocopia Schist",
        "nameDMU": "Orocopia Schist (Cretaceous - Jurassic, 65-165 Ma)",
        "description": "Mostly gray, fine-grained quartz-feldspar-mica schist, with sparse weakly metamorphosed basalt. The unit is exposed in tectonic windows in the southwestern corner of Arizona. It is interpreted as metamorphosed marine sandstone that was tectonically emplaced beneath southwestern Arizona during early Tertiary subduction of Pacific Ocean sea floor.",
        "age": "Cretaceous to Jurassic",
        "b_age": 65,
        "t_age": 165,
        "age_unit": "Ma",
        "rgb": "rgb(186,255,158)"
    },
    "38": {
        "mapunit": "Pz",
        "name": "Paleozoic Sedimentary rocks",
        "nameDMU": "Paleozoic Sedimentary rocks (248-544 Ma)",
        "description": "Undivided Paleozoic limestone, dolostone, quartzite, shale, and related sedimentary rocks.",
        "age": "Paleozoic",
        "b_age": 248,
        "t_age": 544,
        "age_unit": "Ma",
        "rgb": "rgb(123,236,251)"
    },
    "39": {
        "mapunit": "P",
        "name": "Permian Sedimentary rocks",
        "nameDMU": "Permian Sedimentary rocks (270-280 Ma)",
        "description": "Gray to tan, cherty limestone of Kaibab and Toroweap Formations, and underlying white to tan, fine-grained Coconino Sandstone. Limestone was deposited in a shallow sea, and sandstone was deposited in near-shore dunes and beach settings.",
        "age": "Permian",
        "b_age": 270,
        "t_age": 280,
        "age_unit": "Ma",
        "rgb": "rgb(168,240,255)"
    },
    "40": {
        "mapunit": "PP",
        "name": "Permian to Pennsylvanian Sedimentary rocks",
        "nameDMU": "Permian to Pennsylvanian Sedimentary rocks (280-310 Ma)",
        "description": "Interbedded sandstone, shale, and limestone usually characterized by ledgy outcrops. Orange to reddish sandstone forms cliffs near Sedona. This unit includes Supai Group and Hermit Shale in northern Arizona and Naco Group in southern Arizona. It was deposited in coastal-plain to shallow-marine settings during time of variable and changing sea level. Rocks of this map unit in southern Arizona may be in part equivalent to Permian rocks of map unit P in central and northern Arizona.",
        "age": "Permian to Pennsylvanian",
        "b_age": 280,
        "t_age": 310,
        "age_unit": "Ma",
        "rgb": "rgb(158,217,255)"
    },
    "41": {
        "mapunit": "Tby",
        "name": "Pliocene to late miocene Basaltic Rocks",
        "nameDMU": "Pliocene to late miocene Basaltic Rocks (4-8 Ma)",
        "description": "Mostly dark, inconspicuously flat, low-lying or mesa-forming basalt deposited as lava flows. Rocks included in this unit are located almost entirely in the large volcanic fields south and west of Flagstaff, in smaller fields in northwesternmost Arizona, and in the Hopi Buttes volcanic field on the Navajo and Hopi Indian Reservations north of Holbrook. Original volcanic landforms have been obscured by erosion.",
        "age": "Pliocene to Late Miocene",
        "b_age": 4,
        "t_age": 8,
        "age_unit": "Ma",
        "rgb": "rgb(255,186,227)"
    },
    "42": {
        "mapunit": "Tsy",
        "name": "Pliocene to middle Miocene deposits",
        "nameDMU": "Pliocene to middle Miocene deposits (2-16 Ma)",
        "description": "Moderately to strongly consolidated conglomerate and sandstone deposited in basins during and after late Tertiary faulting. Includes lesser amounts of mudstone, siltstone, limestone, and gypsum. These deposits are generally light gray or tan. They commonly form high rounded hills and ridges in modern basins, and locally form prominent bluffs. Deposits of this unit are widely exposed in the dissected basins of southeastern and central Arizona.",
        "age": "Pliocene to Middle Miocene",
        "b_age": 2,
        "t_age": 16,
        "age_unit": "Ma",
        "rgb": "rgb(255,232,196)"
    },
    "43": {
        "mapunit": "Tvy",
        "name": "Pliocene to middle Miocene Volcanic rocks",
        "nameDMU": "Pliocene to middle Miocene Volcanic rocks (2-12 Ma)",
        "description": "Rhyolite to andesite deposited as lava flows and related rocks associated with basaltic rocks of map units Tby and Tb.",
        "age": "Pliocene to Middle Miocene",
        "b_age": 2,
        "t_age": 12,
        "age_unit": "Ma",
        "rgb": "rgb(255,168,255)"
    },
    "44": {
        "mapunit": "YXg",
        "name": "Proterozoic Granitic rocks",
        "nameDMU": "Proterozoic Granitic rocks (1400-1800 Ma)",
        "description": "Undivided Early and Middle Proterozoic granitic rocks (units Xg and Yg).",
        "age": "Proterozoic",
        "b_age": 1400,
        "t_age": 1800,
        "age_unit": "Ma",
        "rgb": "rgb(209,161,119)"
    },
    "45": {
        "mapunit": "Q",
        "name": "Quaternary Surficial deposits, undivided",
        "nameDMU": "Quaternary Surficial deposits, undivided (0-2 Ma)",
        "description": "Unconsolidated to strongly consolidated alluvial and eolian deposits. This unit includes: coarse, poorly sorted alluvial fan and terrace deposits on middle and upper piedmonts and along large drainages; sand, silt and clay on alluvial plains and playas; and wind-blown sand deposits.",
        "age": "Quaternary",
        "b_age": 0,
        "t_age": 2,
        "age_unit": "Ma",
        "rgb": "rgb(244,242,230)"
    },
    "46": {
        "mapunit": "Js",
        "name": "San Rafael Group",
        "nameDMU": "San Rafael Group (Late to Middle Jurassic, about 160-180 Ma)",
        "description": "Commonly cross-bedded, ledge-forming sandstone and slope-forming siltstone. Rock typically has a striped red and white aspect. The Carmel Formation and Entrada Sandstone are prominent members of this group.",
        "age": "Late to Middle Jurassic",
        "b_age": 160,
        "t_age": 180,
        "age_unit": "Ma",
        "rgb": "rgb(121,226,157)"
    },
    "47": {
        "mapunit": "Kmv",
        "name": "Sedimentary rocks of the Upper Cretaceous Mesaverde Group",
        "nameDMU": "Sedimentary rocks of the Upper Cretaceous Mesaverde Group (84-88 Ma)",
        "description": "Gray to buff sandstone with interbedded shale and coal. These rocks, which are similar to slightly younger rocks that form Mesa Verde in southwestern Colorado, were deposited on the margin of a shallow sea. Rocks of this map unit host the only large coal deposits in Arizona.",
        "age": "Upper Cretaceous",
        "b_age": 84,
        "t_age": 88,
        "age_unit": "Ma",
        "rgb": "rgb(232,255,168)"
    },
    "48": {
        "mapunit": "Trcs",
        "name": "Shinarump Conglomerate Member",
        "nameDMU": "Shinarump Conglomerate Member",
        "description": "Basal conglomerate and pebbly sandstone of the Chinle Formation is relatively resistant to erosion and forms extensive benches in some parts of the Colorado Plateau.",
        "age": "Triassic",
        "b_age": 210,
        "t_age": 230,
        "age_unit": "Ma",
        "rgb": "rgb(125,255,209)"
    },
    "49": {
        "mapunit": "TXgn",
        "name": "Tertiary to Early Proterozoic Gneissic rocks",
        "nameDMU": "Tertiary to Early Proterozoic Gneissic rocks (15-1800 Ma)",
        "description": "Gneissic rocks with complex histories, typically with well developed, light-colored granitoid layers and dark-colored biotite- and amphibole-rich layers. Protoliths are of Tertiary to Proterozoic age. This unit includes variably mylonitic gneisses in metamorphic core complexes that have been exhumed from middle crustal levels by large-displacement middle Tertiary normal faults, and gneiss exposed at scattered locations near the Colorado River in southwestern Arizona. These rocks are interpreted to record Proterozoic, Mesozoic, and Tertiary metamorphism and deformation.",
        "age": "Tertiary to Early Proterozoic",
        "b_age": 15,
        "t_age": 1800,
        "age_unit": "Ma",
        "rgb": "rgb(251,154,170)"
    },
    "50": {
        "mapunit": "W",
        "name": "Water",
        "nameDMU": "Water",
        "description": "Water",
        "age": "",
        "b_age": "",
        "t_age": "",
        "age_unit": "",
        "rgb": "rgb(227,249,251)"
    }
}